import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
    { productCode: 'UFTS0010', name: 'Sushi Tray HP 65', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 20 },
    { productCode: 'UFTS0001', name: 'BH-20 Sushi Tray/BX -20', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 20 },
    { productCode: 'UV000008', name: 'Nori Half Size', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UV000009', name: 'Nori Full Size', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UFTP0002', name: 'SFLM-2 LID', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 20 },
    { productCode: 'UFTP0001', name: 'SBM-24C', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 20 },
    { productCode: 'UFHS0001', name: 'Sushi Box', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 50 },
    { productCode: 'UFHP0001', name: 'Poke Bowl Box', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 50 },
    { productCode: 'UV000007', name: 'GINGER', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 15 },
    { productCode: 'UE000013', name: 'Soy Sauce', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 15 },
    { productCode: 'UE000008', name: 'WASABI', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UE000023', name: 'Sugar', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 15 },
    { productCode: 'UE000021', name: 'Vinegar', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 15 },
    { productCode: 'UE000004', name: 'Rice', defaultCategory: 'RAW', defaultUnit: 'PLT', minStockLevel: 5 },
    { productCode: 'UE000003', name: 'Mayonnaise', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UE000031', name: 'Peach', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UFLC0001', name: 'Costco Family Pack California Roll', defaultCategory: 'RTE', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UFLV0001', name: 'Costco Family Pack Veggie Roll', defaultCategory: 'RTE', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UFLA0001', name: 'Takumi Premium Rainbow Combo', defaultCategory: 'RTE', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'UFLP0001', name: 'Poke Bowl label', defaultCategory: 'PKG', defaultUnit: 'ROL', minStockLevel: 5 },
    { productCode: 'UFIN0001', name: 'Ingredion Corn Starch', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 5 },
    { productCode: 'UFTS0002', name: 'BX61', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'FHE00001', name: '15*15*5', defaultCategory: 'PKG', defaultUnit: 'CS', minStockLevel: 10 },
    { productCode: 'FB000012', name: 'Tape', defaultCategory: 'PKG', defaultUnit: 'ROL', minStockLevel: 10 },
    { productCode: 'UFME0001', name: 'Costco 454g CAB Beef Chuck Rolls-USA-V2-327-film', defaultCategory: 'RAW', defaultUnit: 'CS', minStockLevel: 15 },
    { productCode: 'UE000032', name: 'Fine Sugar 20kg/bg', defaultCategory: 'RAW', defaultUnit: 'BG', minStockLevel: 10 },
];
